[versions]
agp = "9.0.0"
kotlin = "2.3.0"
composeBom = "2026.01.00"
coreKtx = "1.17.0"
activityCompose = "1.12.2"
material3 = "1.4.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
activity-compose  = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

compose-bom        = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui         = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
material3          = { module = "androidx.compose.material3:material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library     = { id = "com.android.library",     version.ref = "agp" }
compose-compiler    = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
